In [1]:
from pathlib import Path
import pandas as pd

In [2]:
data_path = Path('LendingClubDataset')/ 'lending_club_loan_two.csv'
data_path1 = Path('LendingClubDataset')/ 'lending_club_info.csv'

df1 = pd.read_csv(data_path1)
df = pd.read_csv(data_path)

In [16]:
pd.set_option('display.max_colwidth', None)
df1

,LoanStatNew,Description
0,loan_amnt,"The listed amount of the loan applied for by the borrower. If at some point in time, the credit department reduces the loan amount, then it will be reflected in this value."
1,term,The number of payments on the loan. Values are in months and can be either 36 or 60.
2,int_rate,Interest Rate on the loan
3,installment,The monthly payment owed by the borrower if the loan originates.
4,grade,LC assigned loan grade
5,sub_grade,LC assigned loan subgrade
6,emp_title,The job title supplied by the Borrower when applying for the loan.*
7,emp_length,Employment length in years. Possible values are between 0 and 10 where 0 means less than one year and 10 means ten or more years.
8,home_ownership,"The home ownership status provided by the borrower during registration or obtained from the credit report. Our values are: RENT, OWN, MORTGAGE, OTHER"
9,annual_inc,The self-reported annual income provided by the borrower during registration.
10,verification_status,"Indicates if income was verified by LC, not verified, or if the income source was verified"
11,issue_d,The month which the loan was funded
12,loan_status,Current status of the loan
13,purpose,A category provided by the borrower for the loan request.
14,title,The loan title provided by the borrower
15,zip_code,The first 3 numbers of the zip code provided by the borrower in the loan application.
16,addr_state,The state provided by the borrower in the loan application
17,dti,"A ratio calculated using the borrower’s total monthly debt payments on the total debt obligations, excluding mortgage and the requested LC loan, divided by the borrower’s self-reported monthly income."
18,earliest_cr_line,The month the borrower's earliest reported credit line was opened
19,open_acc,The number of open credit lines in the borrower's credit file.
20,pub_rec,Number of derogatory public records
21,revol_bal,Total credit revolving balance
22,revol_util,"Revolving line utilization rate, or the amount of credit the borrower is using relative to all available revolving credit."
23,total_acc,The total number of credit lines currently in the borrower's credit file
24,initial_list_status,"The initial listing status of the loan. Possible values are – W, F"
25,application_type,Indicates whether the loan is an individual application or a joint application with two co-borrowers
26,mort_acc,Number of mortgage accounts.
27,pub_rec_bankruptcies,Number of public record bankruptcies

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 396030 entries, 0 to 396029
Data columns (total 24 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   loan_amnt             396030 non-null  float64
 1   term                  396030 non-null  str
 2   int_rate              396030 non-null  float64
 3   installment           396030 non-null  float64
 4   grade                 396030 non-null  str
 5   sub_grade             396030 non-null  str
 6   emp_length            377729 non-null  str
 7   home_ownership        396030 non-null  str
 8   annual_inc            396030 non-null  float64
 9   verification_status   396030 non-null  str
 10  issue_d               396030 non-null  str
 11  loan_status           396030 non-null  str
 12  purpose               396030 non-null  str
 13  dti                   396030 non-null  float64
 14  earliest_cr_line      396030 non-null  str
 15  open_acc              396030 non-null  float64
 16  pub_rec               396030 non-null  float64
 17  revol_bal             396030 non-null  float64
 18  revol_util            395754 non-null  float64
 19  total_acc             396030 non-null  float64
 20  initial_list_status   396030 non-null  str
 21  application_type      396030 non-null  str
 22  mort_acc              358235 non-null  float64
 23  pub_rec_bankruptcies  395495 non-null  float64
dtypes: float64(12), str(12)
memory usage: 72.5 MB

In [3]:
cols_to_drop = ["emp_title","title","address"]
df= df.drop(columns=cols_to_drop)

In [12]:
df.head().T

,0,1,2,3,4
loan_amnt,10000.0,8000.0,15600.0,7200.0,24375.0
term,36,36,36,36,60
int_rate,11.44,11.99,10.49,6.49,17.27
installment,329.48,265.68,506.97,220.65,609.33
grade,B,B,B,A,C
sub_grade,B4,B5,B3,A2,C5
emp_length,10,4,0,6,9
home_ownership,RENT,MORTGAGE,RENT,RENT,MORTGAGE
annual_inc,117000.0,65000.0,43057.0,54000.0,55000.0
verification_status,Not Verified,Not Verified,Source Verified,Not Verified,Verified
issue_d,Jan-2015,Jan-2015,Jan-2015,Nov-2014,Apr-2013
loan_status,0,0,0,0,1
purpose,vacation,debt_consolidation,credit_card,credit_card,credit_card
dti,26.24,22.05,12.79,2.6,33.95
earliest_cr_line,Jun-1990,Jul-2004,Aug-2007,Sep-2006,Mar-1999
open_acc,16.0,17.0,13.0,6.0,13.0
pub_rec,0.0,0.0,0.0,0.0,0.0
revol_bal,36369.0,20131.0,11987.0,5472.0,24584.0
revol_util,41.8,53.3,92.2,21.5,69.8
total_acc,25.0,27.0,26.0,13.0,43.0
initial_list_status,w,f,f,f,f
application_type,INDIVIDUAL,INDIVIDUAL,INDIVIDUAL,INDIVIDUAL,INDIVIDUAL
mort_acc,0.0,3.0,0.0,0.0,1.0
pub_rec_bankruptcies,0.0,0.0,0.0,0.0,0.0

In [5]:
df['loan_status'] = df['loan_status'].replace({"Fully Paid" :0,"Charged Off":1})
df['term']= df['term'].str.replace(" months","").astype(int)

In [11]:
length_change = {"< 1 year":0,
                 "2 years":2,
                 "3 years":3,
                 "4 years":4,
                 "5 years":5,
                 "6 years":6,
                 "7 years":7,
                 "8 years":8,
                 "9 years":9,
                 "10+ years":10 }
df['emp_length'] = df['emp_length'].replace(length_change)

In [14]:
df.isnull().sum()

loan_amnt                   0
term                        0
int_rate                    0
installment                 0
grade                       0
sub_grade                   0
emp_length              18301
home_ownership              0
annual_inc                  0
verification_status         0
issue_d                     0
loan_status                 0
purpose                     0
dti                         0
earliest_cr_line            0
open_acc                    0
pub_rec                     0
revol_bal                   0
revol_util                276
total_acc                   0
initial_list_status         0
application_type            0
mort_acc                37795
pub_rec_bankruptcies      535
dtype: int64